import {cookies} from 'next/headers';

import {Box, ColorModeScript} from '@chakra-ui/react';

import Footer from '@components/layout/Footer';
import Header from '@components/layout/Header';
import {config} from '@hooks/useCustomTheme';

import './globals.scss';
import styles from './layout.module.scss';
import {Providers} from './providers';

import type {Metadata} from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

function RootLayout({children}: RootLayoutProps) {
  const cookieStore = cookies();
  const cookiesString = cookieStore.toString();

  return (
    <html lang='en'>
      <body>
        <Providers cookies={cookiesString}>
          <ColorModeScript initialColorMode={config.initialColorMode} />
          <Box className={styles.app}>
            <Header />
            <main className={styles.main}>{children}</main>
            <Footer />
          </Box>
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout;
